version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  node:
    image: node:latest
    container_name: node-container
    working_dir: /usr/src/app  # Đảm bảo đây là thư mục làm việc trong container
    volumes:
      - .:/usr/src/app  # Mount thư mục hiện tại vào thư mục /usr/src/app trong container
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    command: npm start  # Chạy lệnh khởi động ứng dụng Node.js
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
